routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('tugasakhir', \App\Http\Controllers\TugasakhirController::class);
Route::resource('mahasiswa', \App\Http\Controllers\MahasiswaController::class);
Route::resource('dosen', \App\Http\Controllers\DosenController::class);
Route::resource('topik', \App\Http\Controllers\TopikController::class);

app/Models/Topik.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Topik extends Model
{
    use HasFactory;

    protected $fillable = ['namatopik', 'deskripsi'];
}

app/Http/Controllers/TopikController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Topik;

class TopikController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topiks = Topik::orderBy('id', 'DESC')->paginate(5);
        return view('topik.index', compact('topiks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('topik.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'namatopik' => 'required',
            'deskripsi' => 'required',
        ]);

        $array = $request->only([
            'namatopik', 'deskripsi'
        ]);

        $topiks = Topik::create($array);
        return redirect()->route('topik.index')->with('success_message', 'Berhasil menambahkan Data Topik Baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $topik = Topik::find($id);
        $topiks = Topik::pluck('namatopik', 'namatopik')->all();
        if (!$topik) return redirect()->route('topik.index')
            ->with('error_message', 'Topik dengan id' . $id . ' tidak ditemukan');
        return view('topik.edit', compact('topik'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'namatopik' => 'required',
            'deskripsi' => 'required',

        ]);
        $input = $request->all();
        $topik = Topik::find($id);
        $topik->namatopik = $request->namatopik;
        $topik->deskripsi = $request->deskripsi;
        $topik->save();
        return redirect()->route('topik.index', compact('topik'))
            ->with('success_message', 'Berhasil mengubah Topik');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $topik = Topik::find($id);

        if (!$topik)
            return redirect()->route('topik.index')
                ->with('error_message', 'Data tidak di temukan');
        else $topik->delete();

        return redirect()->route('topik.index')->with('success_message', 'Berhasil menghapus data Topik');
    }
}

resources/views/topik/create.blade.php
@extends('adminlte::page')

@section('title', 'Tambah Topik Tugas Akhir')

@section('content_header')
    <h1 class="m-0 text-darkj">Tambah Topik Tugas Akhir</h1>
@stop
@section('content')
    <form action="{{route('topik.store')}}" method="post">
        @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label for="namatopik">Nama Topik</label>
                        <input type="text" class="form-control @error('namatopik') is-invalid @enderror" id="namatopik" placeholder="Nama Topik" name="namatopik" value="{{old('namatopik')}}">
                        @error('namatopik') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi</label>
                        <input type="text" class="form-control @error('deskripsi') is-invalid @enderror" id="deskripsi" placeholder="Deskripsi Topik" name="deskripsi" value="{{old('deskripsi')}}">
                        @error('deskripsi') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('topik.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/topik/edit.blade.php
@extends('adminlte::page')

@section('title', 'Tambah Topik Tugas Akhir')

@section('content_header')
    <h1 class="m-0 text-darkj">Tambah Topik Tugas Akhir</h1>
@stop
@section('content')
<form action="{{route('topik.update',['topik'=>$topik->id])}}" method="POST">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label for="namatopik">Nama Topik</label>
                        <input type="text" class="form-control @error('namatopik') is-invalid @enderror" id="namatopik" placeholder="Nama topik" name="namatopik" value="{{$topik->namatopik ??('namatopik')}}">
                        @error('namatopik') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="deskripsi">Deskripsi</label>
                        <input type="text" class="form-control @error('deskripsi') is-invalid @enderror" id="deskripsi" placeholder="Deskripsi Topik" name="deskripsi" value="{{$topik->deskripsi ??('deskripsi')}}">
                        @error('deskripsi') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('topik.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/topik/index.blade.php
@extends('adminlte::page')

@section('title', 'Topik Tugas Akhir')

@section('content_header')
<h1>Data Topik Tugas Akhir</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                <a href="{{route('topik.create')}}" class="btn btn-primary mb-2">
                        Tambah Data Topik
                    </a>
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Topik</th>
                            <th>Deskripsi</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($topiks as $key => $topik)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$topik->namatopik}}</td>
                                <td>{{$topik->deskripsi}}</td>
                                <td>
                                    <a href="{{route('topik.edit', $topik)}}" class="btn btn-primary btn-sm">
                                        Edit
                                    </a>
                                    <a href="{{route('topik.destroy', $topik)}}" onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-sm">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop
@push('js')
    <form action="" id="delete-form" method="post">
        @method('delete')
        @csrf
    </form>
    <script>
        $('#example2').DataTable({
            "responsive": true,
        });
        function notificationBeforeDelete(event, el) {
            event.preventDefault();
            if (confirm('Apakah anda yakin akan menghapus data ? ')) {
                $("#delete-form").attr('action', $(el).attr('href'));
                $("#delete-form").submit();
            }
        }
    </script>
@endpush