routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('tugasakhir', \App\Http\Controllers\TugasakhirController::class);
Route::resource('mahasiswa', \App\Http\Controllers\MahasiswaController::class);
Route::resource('dosen', \App\Http\Controllers\DosenController::class);
Route::resource('topik', \App\Http\Controllers\TopikController::class);

app/Models/Dosen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dosen extends Model
{
    use HasFactory;
    /**
     * The attributes that are mass assignable.
     *	
     * @var array
     */
    protected $fillable = [
        'nip', 'namadsn','status','email','nomorhp','idtelegram','alamat'
    ];
}

app/Http/Controllers/DosenController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Dosen;

class DosenController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dosens = Dosen::orderBy('id','DESC')->paginate(5);
        return view('dosen.index',compact('dosens'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dosen.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nip' => 'required',
            'namadsn' => 'required',
            'status' => 'required',
            'email' => 'required',
            'nomorhp' => 'required',
            'idtelegram' => 'required',
            'alamat' => 'required',
        ]);
        $array = $request->only([
            'nip', 'namadsn', 'status', 'email', 'nomorhp', 'idtelegram', 'alamat'
        ]);
        // dd($array);
        //$array['roles'] = $array['roles'][0];
        //$array['password'] = bcrypt($array['password']);
        //dd($array);
        $dosens = Dosen::create($array);
        return redirect()->route('dosen.index')
            ->with('success_message', 'Berhasil menambahkan data dosen baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dosen = Dosen::find($id);
        $dosens = Dosen::pluck('namadsn','namadsn')->all();
        //$userRole = $user->roles->pluck('name','name')->all();
        // dd($user);
        // dd($userRole);
        if (!$dosen) return redirect()->route('dosen.index')
            ->with('error_message', 'dosen dengan id'.$id.' tidak ditemukan');
        return view('dosen.edit', compact('dosen'));
        // return view('managementusers.form', compact('user','roles','userRole'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nip' => 'required',
            'namadsn' => 'required',
            'status' => 'required',
            'email' => 'required',
            'nomorhp' => 'required',
            'idtelegram' => 'required',
            'alamat' => 'required',
        ]);
        $input = $request->all();
        $dosen = Dosen::find($id);
        $dosen->nip = $request->nip;
        $dosen->namadsn = $request->namadsn;
        $dosen->status = $request->status;
        $dosen->email = $request->email;
        $dosen->nomorhp = $request->nomorhp;
        $dosen->idtelegram = $request->idtelegram;
        $dosen->alamat = $request->alamat;
        $dosen->update($input);
        //DB::table('model_has_roles')->where('model_id',$id)->delete();
        //$user->assignRole($request->input('roles'));
       // if ($request->password) $user->password = bcrypt($request->password);
        $dosen->save();
        return redirect()->route('dosen.index',compact('dosen'))
            ->with('success_message', 'Berhasil mengubah dosen');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $dosen = Dosen::find($id);
        //dd($permissionmaster);

        if (!$dosen) 
            return redirect()->route('dosen.index')
            ->with('error_message', 'Data tidak di temukan');
        else $dosen->delete();

        return redirect()->route('dosen.index')->with('success_message','Berhasil menghapus data dosen');
    }
}

resources/views/dosen/create.blade.php
@extends('adminlte::page')

@section('title', 'Tambah Data Dosen')

@section('content_header')
    <h1 class="m-0 text-darkj">Tambah Data Dosen</h1>
@stop
@section('content')
    <form action="{{route('dosen.store')}}" method="post">
        @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="exampleInputNip">NIP</label>
                        <input type="text" class="form-control @error('nip') is-invalid @enderror" id="exampleInputNip" placeholder="Input NIP" name="nip" value="{{old('nip')}}">
                        @error('nip') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputNamaDosen">Nama Dosen</label>
                        <input type="text" class="form-control @error('namadsn') is-invalid @enderror" placeholder="Input Nama Dosen" name="namadsn" value="{{old('namadsn')}}">
                        @error('namadsn') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputStatus">Status</label>
                        <input type="text" class="form-control @error('status') is-invalid @enderror" placeholder="Input Status" name="status" value="{{old('status')}}">
                        @error('status') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail">Email</label>
                        <input type="text" class="form-control @error('email') is-invalid @enderror" placeholder="Input Email" name="email" value="{{old('email')}}">
                        @error('email') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputNomorHp">Nomor HP</label>
                        <input type="text" class="form-control @error('nomorhp') is-invalid @enderror" placeholder="Input Nomor HP" name="nomorhp" value="{{old('nomorhp')}}">
                        @error('nomorhp') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputIdTelegram">ID Telegram</label>
                        <input type="text" class="form-control @error('idtelegram') is-invalid @enderror" placeholder="Input ID Telegram" name="idtelegram" value="{{old('idtelegram')}}">
                        @error('idtelegram') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputAlamat">Alamat</label>
                        <input type="text" class="form-control @error('alamat') is-invalid @enderror" placeholder="Input Alamat" name="alamat" value="{{old('alamat')}}">
                        @error('alamat') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('dosen.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/dosen/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Data Dosen')

@section('content_header')
    <h1 class="m-0 text-dark">Edit Data Dosen</h1>
@stop

@section('content')
<form action="{{route('dosen.update',['dosen'=>$dosen->id])}}" method="POST">
        @method('PUT')
        @csrf
        <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="exampleInputNip">NIP</label>
                        <input type="text" class="form-control @error('nip') is-invalid @enderror" id="exampleInputNip" placeholder="Input NIP" name="nip" value="{{$dosen->nip ??old('nip')}}">
                        @error('nip') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputNamaDosen">Nama Dosen</label>
                        <input type="text" class="form-control @error('namadsn') is-invalid @enderror" placeholder="Input Nama Dosen" name="namadsn" value="{{$dosen->namadsn ??old('namadsn')}}">
                        @error('namadsn') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputStatus">Status</label>
                        <input type="text" class="form-control @error('status') is-invalid @enderror" placeholder="Input Status" name="status" value="{{$dosen->status ??old('status')}}">
                        @error('status') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail">Email</label>
                        <input type="text" class="form-control @error('email') is-invalid @enderror" placeholder="Input Email" name="email" value="{{$dosen->email ??old('email')}}">
                        @error('email') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputNomorHp">Nomor HP</label>
                        <input type="text" class="form-control @error('nomorhp') is-invalid @enderror" placeholder="Input Nomor HP" name="nomorhp" value="{{$dosen->nomorhp ??old('nomorhp')}}">
                        @error('nomorhp') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputIdTelegram">ID Telegram</label>
                        <input type="text" class="form-control @error('idtelegram') is-invalid @enderror" placeholder="Input ID Telegram" name="idtelegram" value="{{$dosen->idtelegram ??old('idtelegram')}}">
                        @error('idtelegram') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputAlamat">Alamat</label>
                        <input type="text" class="form-control @error('alamat') is-invalid @enderror" placeholder="Input Alamat" name="alamat" value="{{$dosen->alamat ??old('alamat')}}">
                        @error('alamat') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('dosen.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/dosen/index.blade.php
@extends('adminlte::page')

@section('title', 'Data Dosen')

@section('content_header')
<h1>Data Dosen</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                <a href="{{route('dosen.create')}}" class="btn btn-primary mb-2">
                        Tambah Data Dosen
                    </a>
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>NIP</th>
                            <th>Nama Dosen</th>
                            <th>Status</th>
                            <th>Email</th>
                            <th>Nomor HP</th>
                            <th>ID Telegram</th>
                            <th>Alamat</th>
                            <th>Opsi</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($dosens as $key => $dosen)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$dosen->nip}}</td>
                                <td>{{$dosen->namadsn}}</td>
                                <td>{{$dosen->status}}</td>
                                <td>{{$dosen->email}}</td>
                                <td>{{$dosen->nomorhp}}</td>
                                <td>{{$dosen->idtelegram}}</td>
                                <td>{{$dosen->alamat}}</td>
                                <td>
                                    <a href="{{route('dosen.edit', $dosen)}}" class="btn btn-primary btn-sm">
                                        Edit
                                    </a>
                                    <a href="{{route('dosen.destroy', $dosen)}}" onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-sm">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop
@push('js')
    <form action="" id="delete-form" method="post">
        @method('delete')
        @csrf
    </form>
    <script>
        $('#example2').DataTable({
            "responsive": true,
        });
        function notificationBeforeDelete(event, el) {
            event.preventDefault();
            if (confirm('Apakah anda yakin akan menghapus data ? ')) {
                $("#delete-form").attr('action', $(el).attr('href'));
                $("#delete-form").submit();
            }
        }
    </script>
@endpush