routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('tugasakhir', \App\Http\Controllers\TugasakhirController::class);
Route::resource('mahasiswa', \App\Http\Controllers\MahasiswaController::class);
Route::resource('dosen', \App\Http\Controllers\DosenController::class);
Route::resource('topik', \App\Http\Controllers\TopikController::class);

app/Models/Mahasiswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mahasiswa extends Model
{
    use HasFactory;

    protected $fillable = ['nimmhs', 'namamhs', 'angkatan', 'email', 'nomorhp', 'idtelegram'];
}

app/Http/Controllers/MahasiswaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Mahasiswa;

class MahasiswaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $mahasiswas = Mahasiswa::orderBy('id', 'DESC')->paginate(5);
        return view('mahasiswa.index', compact('mahasiswas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('mahasiswa.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nimmhs' => 'required',
            'namamhs' => 'required',
            'angkatan' => 'required',
            'email' => 'required',
            'nomorhp' => 'required',
            'idtelegram' => 'required',
        ]);

        $array = $request->only([
            'nimmhs', 'namamhs', 'angkatan', 'email', 'nomorhp', 'idtelegram'
        ]);

        $mahasiswas = Mahasiswa::create($array);
        return redirect()->route('mahasiswa.index')->with('success_message', 'Berhasil menambahkan Data Mahasiswa');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mahasiswa = Mahasiswa::find($id);
        $mahasiswas = Mahasiswa::pluck('namamhs', 'namamhs')->all();
        if (!$mahasiswas)
            return redirect()->route('mahasiswa.index')->with('error_message', 'jabatan dengan id' . $id . 'tidak ditemukan');
        return view('mahasiswa.edit', compact('mahasiswa'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nimmhs' => 'required',
            'namamhs' => 'required',
            'angkatan' => 'required',
            'email' => 'required',
            'nomorhp' => 'required',
            'idtelegram' => 'required',
        ]);

        $input = $request->all();
        $mahasiswas = Mahasiswa::find($id);
        $mahasiswas->nimmhs = $request->nimmhs;
        $mahasiswas->namamhs = $request->namamhs;
        $mahasiswas->angkatan = $request->angkatan;
        $mahasiswas->email = $request->email;
        $mahasiswas->nomorhp = $request->nomorhp;
        $mahasiswas->idtelegram = $request->idtelegram;
        $mahasiswas->update($input);
        $mahasiswas->save();
        return redirect()->route('mahasiswa.index', compact('mahasiswas'))->with('success_message', 'Berhasil mengubah mahasiswa');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $mahasiswa = Mahasiswa::find($id);
        if (!$mahasiswa)
            return redirect()->route('mahasiswa.index')
                ->with('error_message', 'Data tidak di temukan');
        else $mahasiswa->delete();

        return redirect()->route('mahasiswa.index')->with('success_message', 'Berhasil menghapus data mahasiswa');
    }
}

resources/views/mahasiswa/create.blade.php
@extends('adminlte::page')

@section('title', 'Tambah Mahasiswa')

@section('content_header')
    <h1 class="m-0 text-darkj">Tambah Mahasiswa</h1>
@stop
@section('content')
    <form action="{{route('mahasiswa.store')}}" method="post">
        @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label for="nimmhs">NIM</label>
                        <input type="text" class="form-control @error('nimmhs') is-invalid @enderror" id="nimmhs" placeholder="NIM" name="nimmhs" value="{{old('nimmhs')}}">
                        @error('nimmhs') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="namamhs">Nama</label>
                        <input type="text" class="form-control @error('namamhs') is-invalid @enderror" id="namamhs" placeholder="Nama Lengkap" name="namamhs" value="{{old('namamhs')}}">
                        @error('namamhs') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="angkatan">Angkatan</label>
                        <input type="text" class="form-control @error('angkatan') is-invalid @enderror" id="angkatan" placeholder="Input angkatan" name="angkatan" value="{{old('angkatan')}}">
                        @error('angkatan') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" class="form-control @error('email') is-invalid @enderror" id="email" placeholder="Input Email" name="email" value="{{old('email')}}">
                        @error('email') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="nomorhp">Nomor HP</label>
                        <input type="text" class="form-control @error('nomorhp') is-invalid @enderror" id="nomorhp" placeholder="Input Nomor HP" name="nomorhp" value="{{old('nomorhp')}}">
                        @error('nomorhp') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="idtelegram">ID Telegram</label>
                        <input type="text" class="form-control @error('idtelegram') is-invalid @enderror" id="idtelegram" placeholder="Input ID Telegram" name="idtelegram" value="{{old('idtelegram')}}">
                        @error('idtelegram') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('mahasiswa.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/mahasiswa/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Data Mahasiswa')

@section('content_header')
    <h1 class="m-0 text-darkj">Edit Data Mahasiswa</h1>
@stop
@section('content')
    <form action="{{route('mahasiswa.update',['mahasiswa'=>$mahasiswa->id])}}" method="POST">
        @method('PUT')
        @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="form-group">
                        <label for="nimmhs">NIM</label>
                        <input type="text" class="form-control @error('nimmhs') is-invalid @enderror" id="nimmhs" placeholder="NIM" name="nimmhs" value="{{$mahasiswa->nimmhs??old('nimmhs')}}">
                        @error('nimmhs') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="namamhs">Nama</label>
                        <input type="text" class="form-control @error('namamhs') is-invalid @enderror" id="namamhs" placeholder="Nama Lengkap" name="namamhs" value="{{$mahasiswa->namamhs??old('namamhs')}}">
                        @error('namamhs') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="angkatan">Angkatan</label>
                        <input type="text" class="form-control @error('angkatan') is-invalid @enderror" id="angkatan" placeholder="Input angkatan" name="angkatan" value="{{$mahasiswa->angkatan??old('angkatan')}}">
                        @error('angkatan') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="text" class="form-control @error('email') is-invalid @enderror" id="email" placeholder="Input Email" name="email" value="{{$mahasiswa->email??old('email')}}">
                        @error('email') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="nomorhp">Nomor HP</label>
                        <input type="text" class="form-control @error('nomorhp') is-invalid @enderror" id="nomorhp" placeholder="Input Nomor HP" name="nomorhp" value="{{$mahasiswa->nomorhp??old('nomorhp')}}">
                        @error('nomorhp') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="idtelegram">ID Telegram</label>
                        <input type="text" class="form-control @error('idtelegram') is-invalid @enderror" id="idtelegram" placeholder="Input ID Telegram" name="idtelegram" value="{{$mahasiswa->idtelegram??old('idtelegram')}}">
                        @error('idtelegram') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('mahasiswa.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/mahasiswa/index.blade.php
@extends('adminlte::page')

@section('title', 'Data Mahasiswa')

@section('content_header')
<h1>Data Mahasiswa</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                <a href="{{route('mahasiswa.create')}}" class="btn btn-primary mb-2">
                        Tambah Data Mahasiswa
                    </a>
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                        <tr>
                            <th>No</th>
                            <th>NIM</th>
                            <th>Nama Mahasiswa</th>
                            <th>Angkatan</th>
                            <th>Email</th>
                            <th>Nomor HP</th>
                            <th>ID Telegram</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($mahasiswas as $key => $mahasiswa)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$mahasiswa->nimmhs}}</td>
                                <td>{{$mahasiswa->namamhs}}</td>
                                <td>{{$mahasiswa->angkatan}}</td>
                                <td>{{$mahasiswa->email}}</td>
                                <td>{{$mahasiswa->nomorhp}}</td>
                                <td>{{$mahasiswa->idtelegram}}</td>
                                <td>
                                    <a href="{{route('mahasiswa.edit', $mahasiswa)}}" class="btn btn-primary btn-sm">
                                        Edit
                                    </a>
                                    <a href="{{route('mahasiswa.destroy', $mahasiswa)}}" onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-sm">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop
@push('js')
    <form action="" id="delete-form" method="post">
        @method('delete')
        @csrf
    </form>
    <script>
        $('#example2').DataTable({
            "responsive": true,
        });
        function notificationBeforeDelete(event, el) {
            event.preventDefault();
            if (confirm('Apakah anda yakin akan menghapus data ? ')) {
                $("#delete-form").attr('action', $(el).attr('href'));
                $("#delete-form").submit();
            }
        }
    </script>
@endpush