routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('tugasakhir', \App\Http\Controllers\TugasakhirController::class);
Route::resource('mahasiswa', \App\Http\Controllers\MahasiswaController::class);
Route::resource('dosen', \App\Http\Controllers\DosenController::class);
Route::resource('topik', \App\Http\Controllers\TopikController::class);

app/Models/Tugasakhir.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tugasakhir extends Model
{
    use HasFactory;
    /**
     * The attributes that are mass assignable.
     *	
     * @var array
     */
    protected $fillable = [
        'namamhs', 'nimmhs','dospemsatu','dospemdua','topikta','judulta','tanggalmulai','tanggsalselesai'
    ];
}

app/Http/Controllers/TugasakhirController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tugasakhir;
use Illuminate\Http\Request;

class TugasakhirController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tugasakhirs = Tugasakhir::orderBy('id','DESC')->paginate(5);
        return view('tugasakhir.index',compact('tugasakhirs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tugasakhir.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'namamhs' => 'required',
            'nimmhs' => 'required',
            'dospemsatu' => 'required',
            'dospemdua' => 'required',
            'topikta' => 'required',
            'judulta' => 'required',
            'tanggalmulai' => 'required',
            'tanggsalselesai' => 'required',
        ]);
        $array = $request->only([
            'namamhs', 'nimmhs', 'dospemsatu', 'dospemdua', 'topikta', 'judulta', 'tanggalmulai', 'tanggsalselesai'
        ]);
        // dd($array);
        //$array['roles'] = $array['roles'][0];
        //$array['password'] = bcrypt($array['password']);
        //dd($array);
        $tugasakhirs = Tugasakhir::create($array);
        return redirect()->route('tugasakhir.index')
            ->with('success_message', 'Berhasil menambahkan data tugas akhir baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tugasakhir = Tugasakhir::find($id);
        $tugasakhirs = Tugasakhir::pluck('namamhs','namamhs')->all();
        //$userRole = $user->roles->pluck('name','name')->all();
        // dd($user);
        // dd($userRole);
        if (!$tugasakhir) return redirect()->route('tugasakhir.index')
            ->with('error_message', 'tugas akhir dengan id'.$id.' tidak ditemukan');
        return view('tugasakhir.edit', compact('tugasakhir'));
        // return view('managementusers.form', compact('user','roles','userRole'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'namamhs' => 'required',
            'nimmhs' => 'required',
            'dospemsatu' => 'required',
            'dospemdua' => 'required',
            'topikta' => 'required',
            'judulta' => 'required',
            'tanggalmulai' => 'required',
            'tanggsalselesai' => 'required',
        ]);
        $input = $request->all();
        $tugasakhir = Tugasakhir::find($id);
        $tugasakhir->namamhs = $request->namamhs;
        $tugasakhir->nimmhs = $request->nimmhs;
        $tugasakhir->dospemsatu = $request->dospemsatu;
        $tugasakhir->dospemdua = $request->dospemdua;
        $tugasakhir->topikta = $request->topikta;
        $tugasakhir->judulta = $request->judulta;
        $tugasakhir->tanggalmulai = $request->tanggalmulai;
        $tugasakhir->tanggsalselesai = $request->tanggsalselesai;
        $tugasakhir->update($input);
        //DB::table('model_has_roles')->where('model_id',$id)->delete();
        //$user->assignRole($request->input('roles'));
       // if ($request->password) $user->password = bcrypt($request->password);
        $tugasakhir->save();
        return redirect()->route('tugasakhir.index',compact('tugasakhir'))
            ->with('success_message', 'Berhasil mengubah tugas$tugasakhir');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tugasakhir = Tugasakhir::find($id);
        //dd($permissionmaster);

        if (!$tugasakhir) 
            return redirect()->route('tugasakhir.index')
            ->with('error_message', 'Data tidak di temukan');
        else $tugasakhir->delete();

        return redirect()->route('tugasakhir.index')->with('success_message','Berhasil menghapus data mahasiswa');
    }
}

resources/views/tugasakhir/create.blade.php
@extends('adminlte::page')

@section('title', 'Tambah Data Tugas Akhir')

@section('content_header')
    <h1 class="m-0 text-darkj">Tambah Data Tugas Akhir</h1>
@stop
@section('content')
    <form action="{{route('tugasakhir.store')}}" method="post">
        @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="exampleInputNamaMahasiswa">Nama Mahasiswa</label>
                        <input type="text" class="form-control @error('namamhs') is-invalid @enderror" id="exampleInputNamaMahasiswa" placeholder="Input Nama Mahasiswa" name="namamhs" value="{{old('namamhs')}}">
                        @error('namamhs') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputNimMahasiswa">NIM Mahasiswa</label>
                        <input type="text" class="form-control @error('nimmhs') is-invalid @enderror" id="exampleInputNimMahasiswa" placeholder="Input NIM Mahasiswa" name="nimmhs" value="{{old('nimmhs')}}">
                        @error('nimmhs') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDospemsatu">Dosen Pembimbing Satu</label>
                        <input type="text" class="form-control @error('dospemsatu') is-invalid @enderror" id="exampleInputDospemsatu" placeholder="Input Dosen Pembimbing Satu" name="dospemsatu" value="{{old('dospemsatu')}}">
                        @error('dospemsatu') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDospemdua">Dosen Pembimbing Dua</label>
                        <input type="text" class="form-control @error('dospemdua') is-invalid @enderror" id="exampleInputDospemdua" placeholder="Input Dosen Pembimbing Dua" name="dospemdua" value="{{old('dospemdua')}}">
                        @error('dospemdua') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputTopikTa">Topik Tugas Akhir</label>
                        <input type="text" class="form-control @error('topikta') is-invalid @enderror" id="exampleInputTopikTa" placeholder="Input Topik Tugas Akhir" name="topikta" value="{{old('topikta')}}">
                        @error('topikta') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJudulTa">Judul Tugas Akhir</label>
                        <input type="text" class="form-control @error('judulta') is-invalid @enderror" id="exampleInputJudulTa" placeholder="Input Judul Tugas Akhir" name="judulta" value="{{old('judulta')}}">
                        @error('judulta') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputTanggalMulai">Tanggal Mulai Tugas Akhir</label>
                        <input type="text" class="form-control @error('tanggalmulai') is-invalid @enderror" id="exampleInputTanggalMulai" placeholder="Input Judul Tugas Akhir" name="tanggalmulai" value="{{old('tanggalmulai')}}">
                        @error('tanggalmulai') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputTanggalSelesai">Tanggal Selesai Tugas Akhir</label>
                        <input type="text" class="form-control @error('tanggsalselesai') is-invalid @enderror" id="exampleInputTanggalSelesai"  placeholder="Input Judul Tugas Akhir" name="tanggsalselesai" value="{{old('tanggsalselesai')}}">
                        @error('tanggsalselesai') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                       
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('tugasakhir.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/tugasakhir/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Data Tugas Akhir')

@section('content_header')
    <h1 class="m-0 text-dark">Edit Data Tugas Akhir</h1>
@stop

@section('content')
<form action="{{route('tugasakhir.update',['tugasakhir'=>$tugasakhir->id])}}" method="POST">
        @method('PUT')
        @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                <div class="form-group">
                        <label for="exampleInputNamaMahasiswa">Nama Mahasiswa</label>
                        <input type="text" class="form-control @error('namamhs') is-invalid @enderror" id="exampleInputNamaMahasiswa" placeholder="Input Nama Mahasiswa" name="namamhs" value="{{$tugasakhir->namamhs ??old('namamhs')}}">
                        @error('namamhs') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputNimMahasiswa">NIM Mahasiswa</label>
                        <input type="text" class="form-control @error('nimmhs') is-invalid @enderror" id="exampleInputNimMahasiswa" placeholder="Input NIM Mahasiswa" name="nimmhs" value="{{$tugasakhir->nimmhs ??('nimmhs')}}">
                        @error('nimmhs') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDospemsatu">Dosen Pembimbing Satu</label>
                        <input type="text" class="form-control @error('dospemsatu') is-invalid @enderror" id="exampleInputDospemsatu" placeholder="Input Dosen Pembimbing Satu" name="dospemsatu" value="{{$tugasakhir->dospemsatu ??('dospemsatu')}}">
                        @error('dospemsatu') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputDospemdua">Dosen Pembimbing Dua</label>
                        <input type="text" class="form-control @error('dospemdua') is-invalid @enderror" id="exampleInputDospemdua" placeholder="Input Dosen Pembimbing Dua" name="dospemdua" value="{{$tugasakhir->dospemdua ??('dospemdua')}}">
                        @error('dospemdua') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputTopikTa">Topik Tugas Akhir</label>
                        <input type="text" class="form-control @error('topikta') is-invalid @enderror" id="exampleInputTopikTa" placeholder="Input Topik Tugas Akhir" name="topikta" value="{{$topikta->name ??('topikta')}}">
                        @error('topikta') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputJudulTa">Judul Tugas Akhir</label>
                        <input type="text" class="form-control @error('judulta') is-invalid @enderror" id="exampleInputJudulTa" placeholder="Input Judul Tugas Akhir" name="judulta" value="{{$tugasakhir->judulta ??('judulta')}}">
                        @error('judulta') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputTanggalMulai">Tanggal Mulai Tugas Akhir</label>
                        <input type="text" class="form-control @error('tanggalmulai') is-invalid @enderror" id="exampleInputTanggalMulai" placeholder="Input Judul Tugas Akhir" name="tanggalmulai" value="{{$tugasakhir->tanggalmulai ??('tanggalmulai')}}">
                        @error('tanggalmulai') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                    <div class="form-group">
                        <label for="exampleInputTanggalSelesai">Tanggal Selesai Tugas Akhir</label>
                        <input type="text" class="form-control @error('tanggsalselesai') is-invalid @enderror" id="exampleInputTanggalSelesai"  placeholder="Input Judul Tugas Akhir" name="tanggsalselesai" value="{{$tugasakhir->tanggsalselesai ??('tanggsalselesai')}}">
                        @error('tanggsalselesai') <span class="text-danger">{{$message}}</span> @enderror
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('tugasakhir.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/tugasakhir/index.blade.php
@extends('adminlte::page')

@section('title', 'Data Tugas Akhir')

@section('content_header')
<h1>Data Tugas Akhir</h1>
@stop
@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                <a href="{{route('tugasakhir.create')}}" class="btn btn-primary mb-2">
                        Tambah Data Tugas Akhir
                    </a>
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama</th>
                            <th>NIM</th>
                            <th>Dosen Pembimbing 1</th>
                            <th>Dosen Pembimbing 2</th>
                            <th>Topic</th>
                            <th>Judul</th>
                            <th>Tanggal Mulai</th>
                            <th>Tanggal Selesai</th>
                            <th>Opsi</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($tugasakhirs as $key => $tugasakhir)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$tugasakhir->namamhs}}</td>
                                <td>{{$tugasakhir->nimmhs}}</td>
                                <td>{{$tugasakhir->dospemsatu}}</td>
                                <td>{{$tugasakhir->dospemdua}}</td>
                                <td>{{$tugasakhir->topikta}}</td>
                                <td>{{$tugasakhir->judulta}}</td>
                                <td>{{$tugasakhir->tanggalmulai}}</td>
                                <td>{{$tugasakhir->tanggsalselesai}}</td>
                                <td>
                                    <a href="{{route('tugasakhir.edit', $tugasakhir)}}" class="btn btn-primary btn-sm">
                                        Edit
                                    </a>
                                    <a href="{{route('tugasakhir.destroy', $tugasakhir)}}" onclick="notificationBeforeDelete(event, this)" class="btn btn-danger btn-sm">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop
@push('js')
    <form action="" id="delete-form" method="post">
        @method('delete')
        @csrf
    </form>
    <script>
        $('#example2').DataTable({
            "responsive": true,
        });
        function notificationBeforeDelete(event, el) {
            event.preventDefault();
            if (confirm('Apakah anda yakin akan menghapus data ? ')) {
                $("#delete-form").attr('action', $(el).attr('href'));
                $("#delete-form").submit();
            }
        }
    </script>
@endpush